### Save with anonymous session
POST http://localhost:3001/api/builds
Content-Type: application/json
X-Anonymous-Session: 436472cd-4f02-40c7-ab95-72657c9eb18e

{
  "title": "TestAnon",
  "character": {
    "name": "Test Anonymous",
    "gender": "male",
    "startingClass": "pyromancer",
    "humanity": 10,
    "attributes": {
      "vitality": 23,
      "attunement": 12,
      "endurance": 16,
      "strength": 17,
      "dexterity": 16,
      "resistance": 13,
      "intelligence": 16,
      "faith": 99
    }
  }
}

### Save with logged session: mluukkai
POST http://localhost:3001/api/builds
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2N2Q1MDNhOGZmMzRiNWMyMjc2MjIzNTgiLCJpYXQiOjE3NDIwOTkyMjgsImV4cCI6MTc0MjE0MjQyOH0.wHbEJtvu_gz9SKirlSgo5g-slQWrUPVtVtN4SUmD7u0

{
  "title": "TestLogged",
  "character": {
    "name": "Test mluukkai",
    "gender": "male",
    "startingClass": "pyromancer",
    "humanity": 10,
    "attributes": {
      "vitality": 23,
      "attunement": 12,
      "endurance": 16,
      "strength": 17,
      "dexterity": 16,
      "resistance": 13,
      "intelligence": 16,
      "faith": 99
    }
  }
}

