### Delete with anonymous session
DELETE http://localhost:3001/api/builds/dark-souls-1/67d737746cc285c6b2a49c8b
Content-Type: application/json
X-Anonymous-Session: 934d0af9-aed9-42ba-9e50-ec9d1dea1f8c

### Delete with logged session: mluukkai
DELETE http://localhost:3001/api/builds/dark-souls-1/67d7afc8e3dde151cab86f06
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2N2Q1MDNhOGZmMzRiNWMyMjc2MjIzNTgiLCJpYXQiOjE3NDIxNTEyMzksImV4cCI6MTc0MjE5NDQzOX0.WKjRWiIllByCfGrU9kiER-Z_sSYX5AAG1F3uTs6Y_ZE