### Save with logged session: mluukkai
PUT http://localhost:3001/api/builds/dark-souls-1/67db0beda577d3e061a69eb2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2N2Q1MDNhOGZmMzRiNWMyMjc2MjIzNTgiLCJpYXQiOjE3NDI0MDg2NjUsImV4cCI6MTc0MjQ1MTg2NX0.X-pnx9CE_UIzLwd_G9HOIDRj20b1alpfM07WD_HhHno

{
  "title": "DS1BuildTest",
  "character": {
    "name": "mlukkaiDS1",
    "gender": "male",
    "startingClass": "pyromancer",
    "humanity": 10,
    "attributes": {
      "vitality": 30,
      "attunement": 12,
      "endurance": 16,
      "strength": 17,
      "dexterity": 16,
      "resistance": 13,
      "intelligence": 16,
      "faith": 99
    }
  }
}
